finish android

diff --git a/contrib/bootstrap b/contrib/bootstrap
--- a/contrib/bootstrap
+++ b/contrib/bootstrap
@@ -213,26 +213,54 @@ check_macosx_sdk()
 
 check_android_sdk()
 {
+        ANDROID_ABI=$MY_TARGET_ARCH
+        
 	[ -z "${ANDROID_NDK}" ] && echo "You must set ANDROID_NDK environment variable" && exit 1
 	add_make "ANDROID_NDK := ${ANDROID_NDK}"
+	[ -z "${ANDROID_GCC_VERSION}" ] && echo "You must set ANDROID_GCC_VERSION environment variable" && exit 1
+	add_make "ANDROID_GCC_VERSION := ${ANDROID_GCC_VERSION}"
 	[ -z "${ANDROID_ABI}" ] && echo "You must set ANDROID_ABI environment variable" && exit 1
 	add_make "ANDROID_ABI := ${ANDROID_ABI}"
 	[ -z "${ANDROID_API}" ] && echo "You should set ANDROID_API environment variable (using default android-9)" && ANDROID_API := android-9
 	add_make "ANDROID_API := ${ANDROID_API}"
+        
+        ## FIXME: the android toolchain path is hardcoded, only MACOSX will work.
+        if [ ${ANDROID_ABI} = "x86" ]; then
+            toolchain_path_prefix=x86
+        elif [ ${ANDROID_ABI} = "arm64" ];then
+            toolchain_path_prefix=aarch64-linux-android
+        else
+            toolchain_path_prefix=arm-linux-androideabi
+        fi
 
-	if [ ${ANDROID_ABI} = "armeabi-v7a" ]; then
+        # check whether gcc version is exists
+        if [ ! -d ${ANDROID_NDK}/toolchains/${toolchain_path_prefix}-${ANDROID_GCC_VERSION} ] ;then
+            echo ${ANDROID_NDK}
+            echo "Invalid GCC ${ANDROID_GCC_VERSION} version!"
+            exit
+        fi
+
+        # check whether sysroot is exists
+        if [ $ANDROID_ABI = "arm64" ]; then
+            if [ ! -d ${ANDROID_NDK}/platforms/${ANDROID_API}/arch-arm64 ];then
+                echo "${ANDROID_NDK} ${ANDROID_API} doesn't support build arm64 architecture!"
+                exit 1
+            fi
+        fi
+
+	if [ ${ANDROID_ABI} = "armv7" ]; then
             add_make_enabled "HAVE_NEON"
             add_make_enabled "HAVE_ARMV7A"
             add_make "EXTRA_CFLAGS := -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb -fomit-frame-pointer -fno-strict-aliasing -DANDROID  -Wa,--noexecstack -Wformat "
             add_make "EXTRA_LDFLAGS := -march=armv7-a -Wl,--fix-cortex-a8"
         fi
         
-	if [ ${ANDROID_ABI} = "armeabi" -a -z "${NO_ARMV6}" ];then
+	if [ ${ANDROID_ABI} = "arm" -a -z "${NO_ARMV6}" ];then
             add_make_enabled "HAVE_ARMV6"
             add_make "EXTRA_CFLAGS := -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes  -march=armv5te -mtune=xscale -msoft-float -mthumb -fomit-frame-pointer -fno-strict-aliasing -DANDROID  -Wa,--noexecstack -Wformat "
         fi
 
-	if [ ${ANDROID_ABI} = "arm64-v8a" ]; then
+	if [ ${ANDROID_ABI} = "arm64" ]; then
             add_make_enabled "HAVE_NEON"
             add_make_enabled "HAVE_ARMV8A"
             add_make "EXTRA_CFLAGS :=  -fpic -ffunction-sections  -funwind-tables  -fstack-protector  -no-canonical-prefixes"
